export let routes = [
  {
    path: '/info',
    handler: 'getAll',
    helper: 'auth',
    type: 'get',
    params: {},
  },
  {
    path: '/match',
    handler: 'getAll',
    helper: 'auth',
    type: 'get',
    params: [
      { path: 'players goals.scorer goals.passer', select: 'name url -_id' },
      { path: 'season', select: 'date url -_id' },
    ],
  },
  {
    path: '/match/:id',
    handler: 'getOne',
    helper: 'auth',
    type: 'get',
    params: [
      { path: 'players goals.scorer goals.passer', select: 'name url -_id' },
      { path: 'season', select: 'date url -_id' },
    ],
  },
  {
    path: '/player',
    handler: 'getAll',
    helper: 'auth',
    type: 'get',
    params: { path: 'trophies', select: 'competition date url -_id' },
  },
  {
    path: '/player/:id',
    handler: 'getOne',
    helper: 'auth',
    type: 'get',
    params: { path: 'trophies', model: 'Trophy', select: 'competition date url -_id' },
  },
  {
    path: '/player/:id/matches',
    handler: 'getMatches',
    helper: 'auth',
    type: 'get',
    params: 'players',
  },
  {
    path: '/coach',
    handler: 'getAll',
    helper: 'auth',
    type: 'get',
    params: { path: 'trophies', select: 'competition date url -_id' },
  },
  {
    path: '/coach/:id',
    handler: 'getOne',
    helper: 'auth',
    type: 'get',
    params: { path: 'trophies', select: 'competition date url -_id' },
  },
  {
    path: '/president',
    handler: 'getAll',
    helper: 'auth',
    type: 'get',
    params: {
      path: 'trophies',
      model: 'Trophy',
      select: 'competition date url -_id',
    },
  },
  {
    path: '/president/:id',
    handler: 'getOne',
    helper: 'auth',
    type: 'get',
    params: {
      path: 'trophies',
      model: 'Trophy',
      select: 'competition date url -_id',
    },
  },
  {
    path: '/owner',
    handler: 'getAll',
    helper: 'auth',
    type: 'get',
    params: '',
  },
  {
    path: '/owner/:id',
    handler: 'getOne',
    helper: 'auth',
    type: 'get',
  },
  {
    path: '/season',
    handler: 'getAll',
    helper: 'auth',
    type: 'get',
    params: '',
  },
  {
    path: '/season/:id',
    handler: 'getOne',
    helper: 'auth',
    type: 'get',
  },
  {
    path: '/season/:id/matches',
    handler: 'getMatches',
    helper: 'auth',
    type: 'get',
    params: 'season',
  },
  {
    path: '/trophy',
    handler: 'getAll',
    helper: 'auth',
    type: 'get',
    params: { path: 'season', model: 'Season', select: 'date url' },
  },
  {
    path: '/trophy/:id',
    handler: 'getOne',
    helper: 'auth',
    type: 'get',
    params: { path: 'season', model: 'Season', select: 'date url' },
  },
];
